### PR TITLE
More advanced spying :)

### PR DESCRIPTION
**Pull request by pawelzwronek**
A: enque spy mission to avoid too fast clicking
A: wait for free mission slot
Now you can click as fast as you can and as many as you want :)

### CODE REVIEW

**Comment by pawelzwronek** [comment]
TODO: save the queue to the config and process it everywhere in a background. Not to many articles 'a' and 'the'. I've always dilemma while using it :P

**Comment by eswak** [comment]
a queue system would be insanely cool, we could even queue mine building tasks :P

**Comment by eswak** [comment]
by the way thanks for respecting the coding style (`.eslintrc.json`), your PRs are clean & easy to review ❤️

**Comment by eswak** [comment]
Merged ! Thanks ^^

I really like how you did the icon color changing thing.

I just updated 2 things before merging : 
 - removed logs
 - added `Math.round` in the message "waiting x seconds for a free slot"

**Comment by pawelzwronek** [comment]
https://stackoverflow.com/questions/36679649/how-to-add-a-color-overlay-to-a-background-image  :P

**Pull request closed without merging**
