### PR TITLE
A: polish flag in README.md

### PR DESCRIPTION
**Pull request by pawelzwronek**

### CODE REVIEW

**Comment by eswak** [comment]
lol

**Comment by eswak** [comment]
you deserve it well :^p

**Comment by pawelzwronek** [comment]
Thx. Unfortunately there was not :pl: flag in emojis so I've to photoshop :ru: flag :P Also vertical alignment is not perfect :( Maybe I'll fix it in the future.

**Comment by eswak** [comment]
you mean like 🇵🇱 ? 😉 `:poland:`

**Comment by pawelzwronek** [comment]
How did you find id ? 😕

**Comment by eswak** [comment]
I just tried and it showed up in autocompletion x)
You can find lists of github emojis on the internet though

**Comment by eswak** [comment]
by the way I like what you added in your score logger (the checkboxes for charts on the right). I use your tool daily, really ^^

I wonder if we could automatically detect astrophysics upgrades & mine upgrades using research & economy scores

**Comment by pawelzwronek** [comment]
I was here https://www.webpagefx.com/tools/emoji-cheat-sheet/  but no luck. It's  some kind of secret or undocumented yet feature ;)

**Pull request merged**
