### PR TITLE
A: support for AntiGameOrigin v6 extension

### PR DESCRIPTION
**Pull request by pawelzwronek**
While AntiGameOrigin v6 enable some UI++ features are broken so created new branch to fix it. More fixes soon :)

### CODE REVIEW

**Comment by eswak** [comment]
I tried this extension but didn't like it because it changes the whole UI

What features do you like in AntiGameOrigin that we don't have in this extension ? I'm curious ^^

**Comment by pawelzwronek** [comment]
Most of all I like very compact spy reports list. Original is too much chaotic for me :) Also on the planets list I can see what is under construction on every planet. Handy list of targets is also useful. Tab 'Account' is useful too.

**Comment by pawelzwronek** [comment]
So you are not into making fixes to improve compatibility with others extensions or you just dont like way I made it? I've should put some comment.

**Comment by pawelzwronek** [comment]
P.S. I dont like those waiting PR especially #11 :)

**Comment by eswak** [comment]
Yup I'm closing #11 

I don't use any other extensions (obviously), if I miss something I add it in this extension ^^
Plus, I really really really dislike AGOv6, it completely breaks the interface adding ugly buttons & text everywhere.

I don't mind that you wanna make the OGame UI++ extension compatible with AGOv6 though if you like AGO. But I thought you were going to add more commits and that this PR was more like a "work in progress" ^^

I'll have free time tonight so I'll make my best to close all PRs in progress.
I'll install AGO & test this one as well.

Sorry that you felt your PR wasn't given enough attention, I just thought it was a work in progress 😭

**Comment by pawelzwronek** [comment]
😀

**Comment by cmartinezledo** [comment]
I agree with @pawelzwronek, the spy section is really nice. I still think 'Skynet' had a better one, but the extension seems to be forgotten.

**Pull request merged**
