### PR TITLE
A: time left to storage get full in statistic tab

### PR DESCRIPTION
**Pull request by pawelzwronek**
How do u like it? Maybe factor of opacity could be changed.

### CODE REVIEW

**Comment by eswak** [comment]
I don't like it that much, it loads the interface even more :-/

Not sure how we could fit the information in the interface, there is not much width left

For me the main question is "when is my next storage full, and which resource on which planet ?"
maybe the next 3 storages going full with planet & time info would be sufficient.

not sure where to put this either, though.

**Comment by eswak** [comment]
maybe like this ? top 3 storage of each resource that will be full

(the resources in flight is something I added this evening, be sure to pull master to get it ^^)

stats-storagetime

**Comment by pawelzwronek** [comment]
You are right, the IF would be too cluttered and I like your idea. 
How about dimmed resources icons? I think now contrast it's too big. Also moved fullIn time on a res icon so the planets names can be displayed.
dimmed res

**Comment by eswak** [comment]
looks good 👍 i'll definetely merge that this evening

**Pull request closed without merging**
