### PR TITLE
OGame UI++ v2.0.0

### PR DESCRIPTION
**Pull request by eswak**
- [x] Add util functions
- [x] Add trend to alliance tab
alliance
- [x] Add server-wide top10 / flop10 (it could be fun to see who lost the most fleet or had the biggest economy growth on a day-to-day basis)
topfloptab
- [x] Add trend to neighbors tab
neighbours
- [x] Add current-player chart for global/economy/military score evolution (war-riders like, but for local history only (7 points))
stats
- [x] Buttons to reset planet stats, notes, etc, in settings page (not just clear all)
- [x] Add Paypal donation button in settings tab (maybe someone will offer me a coffee...)
settings
- [x] Add Google Analytics for future feature inspirations

### CODE REVIEW

**Comment by pawelzwronek** [comment]
Every table looks great :) Numbers, numbers, gime more numbers (⊙_◎)
One suggestion: in top/flop a button with a field to change the numbers of days when you want so see most recent changes. What you think?

**Comment by eswak** [comment]
why not :-)

**Comment by eswak** [comment]
I like the fact that it changes everyday though

**Comment by eswak** [comment]
by the way @pawelzwronek I tested chartist.js, it doesn't come with a lot of features (like, stacked area charts are missing) and the tooltip plugin is kind of crap...

I'm using Highcharts at work that does a lot more, but it's a lot heavier and requires more code to work so I'd rather keep chartist for now ^^ 

thanks for the library suggestion

**Comment by eswak** [comment]
here we go

**Pull request merged**
