### PR TITLE
We should see all planets

### PR DESCRIPTION
**Pull request by ggcatu**
THIS PULL IS NOT READY TO BE MERGED

Ignoring the window.getAllPlanets = function

I'm having a problem trying to display all planets from a user.
Basically If im on the galaxy view,  I would like to be able to see all the player planets when i hover on the player name.

Whats the main problem?
$(window).bind("load", function() {...
Seems to be called only ONCE , after that you need to reload the plugin so it works?

I don't know what i'm missing. .

---------------------------------

Seems like ogame whenever you navigate through tabs, doesn't reload website, 
setInterval made the trick. Now i need  a way to hook to galaxy movements (Chagne galaxy, change system) so i call the function again.

---------------------------------

BOY IS WORKING!
We just need to fix, that sometimes, planet names get a little messy inside the window when some player has more than 1 planet in the same galaxy, since $('#'+id) don't care about order.

image

THIS PULL IS NOT READY TO BE MERGED

### CODE REVIEW

**Comment by cmartinezledo** [comment]
Good code @ggcatu 
Seems like you are making something similar to UniverseView Extension.

Also.. did you try it with players that relocate their planets?

**Comment by ggcatu** [comment]
It should work, but update only after 1 week, we could also add a button to update individual players but havent worked on this more hehehe
maybe i will finish it soon

**Comment by ggcatu** [comment]
Ready for merge.

**Comment by cmartinezledo** [comment]
@eswak Could you merge this?

**Comment by eswak** [comment]
I'm not so happy with the coding style & the commits, but I'll give it a try asap and if it works properly, I'll merge & rebase the commits afterwards ^^

thanks for commenting on this pull-request, it totally went out of my mind

**Comment by eswak** [comment]
I included your code snippet in the 1.7.0 release.
It does not refresh player data by getting `/api/playerData.xml` though, because this API updates [once a week](https://board.origin.ogame.gameforge.com/index.php/Thread/3927-OGame-API/) which is already the rate we refresh data at. You were not getting fresher data this way.

Hope you'll like it.

capture d ecran 2017-06-05 a 20 03 49

**Pull request closed without merging**
