### PR TITLE
CHG: sort table immediately to avoid flickering on first visit of idles tab

### PR DESCRIPTION
**Pull request by pawelzwronek**

### CODE REVIEW

**Comment by eswak** [comment]
thanks for the very clean diff :-)

**Comment by pawelzwronek** [comment]
You are welcome.
One question. What IDE do u use? Lately I've installed VS Code and Atom to compare them. Code seems to be more interesting to me, it's quicker first of all.

**Comment by eswak** [comment]
I use Atom, I like how it is "hackable" (there is a huge community that make plugins, and you can override everything in the config files). The new version comes with a lot of github features natively integrated in Atom, and it's even better. I don't need the github desktop app anymore (I still use CLI for rebase though).

Some of my colleagues use Jetbrain's WebStorm, which has a lot of built-in features; but I find it too bulky.

**Comment by pawelzwronek** [comment]
I see, I've moved from notepad++ so it's big improvement to me :P I've tried Atom for about 10 min and it looks a little to heavy and slow to me but solution would be investment in new laptop...
Now I'm happy with ultra fast Code and I love configuring everything in configs files in JSON format and even on hover on chosen setting I get help tooltip 😀

**Pull request merged**
