### PR TITLE
New feature: filtering buttons with time of flight of Large Tarnsporter back and forth

### PR DESCRIPTION
**Pull request by pawelzwronek**
What do you think about filtering list of nearby idles? It was easy for me to add only predefined buttons but I think it's quite fast and easy.

### CODE REVIEW

**Comment by eswak** [comment]
this feature has been asked on google chrome store's comments, so i guess it's a good idea !

the best would be to also parse the technology level when in the research tab, so the flight time would be accurate

**Comment by eswak** [comment]
can you include a screenshot of your changes ?

**Comment by pawelzwronek** [comment]
done including calculating research level of combustion drive
screen4

**Comment by eswak** [comment]
looks good ^^

would you be ok if I merge it & change a few things before publishing ? I'm not sure about the way flight time is displayed, and i'd like to extend the button-filter system you made to add more filters

**Comment by pawelzwronek** [comment]
Yeah sure. I noticed flight time isn't correct so I'm repair it right now.

W dniu 2017-06-13 o 19:47, Erwan Beauvois pisze:

**Comment by eswak** [comment]
alright

by the way; you should divide `V` by `Number($('[name=ogame-universe-speed-fleet]').attr('content'))` (which is the universe speed multiplier for fleets), otherwise it won't work on speed-boosted universe (like mine !)

**Comment by pawelzwronek** [comment]
All done. Flight time corrected including universe-speed-fleet.

screen5

**Comment by eswak** [comment]
thank you !

I'll merge & publish this evening

**Comment by eswak** [comment]
I merged locally and it seems there are still things i'd like to see changed in your PR (sorry I didn't give it an in-depth review first... I basically looked at the picture) : 
- please use soft tabs (spaces), you're sometimes using `\t` and I see a lot of mis-indented additions in your submitted code. You could also rebase your commits in order to get a cleaner history.
- the flight time is incorrect (way too high), I think there may be a flaw in the formulas.
  - by the way I misled you, the universe speed should be applied on the flight time result & not on the ships' speed
- you should make a separate function (that you could name `uipp_getDistance`) that takes two coordinates as arguments (ex: `uipp_getDistance([2, 80, 12], [1, 182, 6])` that returns a `Number` in order to compute distance. It could be used somewhere else that way.
- same goes for a function that could be named `uipp_getFlightTime(speed, distance)` and it should return duration in seconds like other time functions do
  - you could put these functions in a separate file e.g. `src/utils/formulas.js` where we'll store all the game-engine-related formulas (like production for a given level of a mine, etc)

doing these changes would result in a way simpler code addition in `tab-idles.js` : 
```js
idles.push({
  id: playerId,
  name: player.name,
  coords: planet.coords,
  economyScore: player.economyScore,
  militaryScore: player.militaryScore,
  ships: player.ships,
  flightTime: uipp_getFlightTime(7500, uipp_getDistance(myCoords, planet.coords))
});

// + html changes
```

I also noticed a performance issue (browser freeze) using the filter buttons you added on top of the list. I suggest that you remove the filter buttons. This may seem a little overkill, but I'm working on an improvement that makes the tables sortable (by clicking the headers), so we basically could use the "sort by flight time" feature & don't need a filter anymore. I don't like the "invisible menu button programmatical click" either, you should do something simpler (like filter the `idles` array & move the html generation to a separate function that could get called upon array filter)


sorry i'm a little picky for some details, but sometimes I'm not committing changes on this extension for months so the code have to be organized & have a consistent writing style

**Comment by pawelzwronek** [comment]
Done :)
- tabs fixed
- for me flight time is correct, but keep in mind it's doubled one way flight time and of course it's valid only for large transporters
- freeze happens when you select large period eg. 8h and list is getting huge. I dont get how sorting would resolve this :(

**Comment by eswak** [comment]
I'll merge for now & have a look at the performance before publishing

Thanks a lot for your contribution ^^

**Comment by eswak** [comment]
manually merged on master because of the conflicts

**Pull request closed without merging**
